# Mapeamento correto de títulos dos blocos da LC 214/2025
BLOCOS_TITULOS = {
    1: "Disposições preliminares",
    2: "Operações com bens e serviços: incidência, imunidades, fato gerador, local e base",
    3: "Alíquotas: padrão e referência",
    4: "Sujeição passiva (contribuinte e responsáveis)",
    5: "Extinção do débito: pagamento, split payment, recolhimento por adquirente e responsável",
    6: "Pagamento indevido/maior e ressarcimento",
    7: "Regimes de apuração",
    8: "Não cumulatividade e uso/consumo pessoal",
    9: "Operacionalização: cadastro único, DF-e e cidadania fiscal",
    10: "IBS/CBS na importação (regras gerais e não cumulatividade)",
    11: "IBS/CBS na exportação",
    12: "Regimes aduaneiros especiais, bagagem/remessas e combustível aeronave (tráfego internacional)",
    13: "ZPE (Zonas de Processamento de Exportação)",
    14: "Regimes de bens de capital (Reporto, Reidi, Renaval e desoneração)",
    15: "Cashback (devolução personalizada IBS/CBS)",
    16: "Cesta Básica Nacional de Alimentos",
    17: "Regimes diferenciados: regras gerais + redução de 30% + estrutura da redução de 60%",
    18: "Redução de 60%: Educação e Saúde",
    19: "Redução de 60%: Dispositivos médicos, acessibilidade e medicamentos",
    20: "Redução de 60%: Alimentos, higiene/limpeza baixa renda, agro in natura, insumos e demais setores listados",
    21: "Alíquota zero: regras gerais e itens listados (inclui automóveis PCD/táxi)",
    22: "Alíquota zero: ICT sem fins lucrativos, transporte público urbano e reabilitação urbana",
    23: "Não contribuintes específicos: produtor rural, TAC PF, reciclagem/logística reversa e bens usados",
    24: "Regime específico: combustíveis (monofásico, base por quantidade, créditos etc.)",
    25: "Regime específico: serviços financeiros (inclui importação/exportação e transitórias)",
    26: "Regime específico: planos de assistência à saúde + concursos de prognósticos",
    27: "Regime específico: bens imóveis (base, redutores, alíquota, incorporação, sujeito passivo)",
    28: "Regimes específicos diversos e disposições comuns (coops, bares/restaurantes, hotelaria/parques, transportes, turismo, SAF, diplomáticas/tratados)",
    29: "Regimes diferenciados da CBS (PROUNI e regime automotivo)",
    30: "Administração IBS/CBS (regulamento, harmonização, fiscalização, DTE, presunções, doc fiscal, REF)",
    31: "Transição: fixação de alíquotas 2026 + alíquotas de referência 2027–2035 + redutor Adm. Pública",
    32: "Transição: limite redução IBS (2029–2077) + compras gov + reequilíbrio + saldo credor PIS/COFINS",
    33: "Transição: compensação benefícios ICMS + transição bens de capital + disposições finais do título",
    34: "Imposto Seletivo (IS): estrutura completa",
    35: "ZFM, Áreas de Livre Comércio e devolução ao turista estrangeiro + compras governamentais + transitórias",
    36: "Fechamento da LC: avaliação quinquenal, compensações, Comitê Gestor do IBS, transição bens imóveis e disposições finais"
}
