# Mapeamento correto de títulos dos blocos da LC 214/2025
# Total: 32 blocos
# Versão: Títulos resumidos para melhor usabilidade

BLOCOS_TITULOS = {
    1: "Disposições Preliminares",
    2: "Operações Tributáveis",
    3: "Contribuintes e Responsáveis",
    4: "Base de Cálculo e Alíquotas",
    5: "Alíquotas de Referência",
    6: "Sujeição Passiva",
    7: "Regimes Diferenciados",
    8: "Cesta Básica Nacional",
    9: "Cesta Estendida",
    10: "Saúde e Educação",
    11: "Serviços Financeiros",
    12: "Planos de Saúde",
    13: "Transporte",
    14: "Combustíveis e Energia",
    15: "Bens Imóveis",
    16: "Economia Digital",
    17: "Operações Internacionais",
    18: "Cashback",
    19: "Não Cumulatividade",
    20: "Ressarcimento e Compensação",
    21: "Obrigações Acessórias",
    22: "Apuração e Recolhimento",
    23: "Penalidades",
    24: "Processo Administrativo",
    25: "Comitê Gestor do IBS",
    26: "Distribuição de Receitas",
    27: "Fundos de Compensação",
    28: "Regimes Específicos",
    29: "Regimes Favorecidos",
    30: "Administração da CBS",
    31: "Disposições Transitórias",
    32: "Disposições Finais",
}

# Títulos completos oficiais (para referência)
BLOCOS_TITULOS_COMPLETOS = {
    1: "DISPOSIÇÕES PRELIMINARES – ESTRUTURA DO IBS E DA CBS",
    2: "OPERAÇÕES TRIBUTÁVEIS, BENS E SERVIÇOS",
    3: "CONTRIBUINTES, RESPONSÁVEIS E SUJEIÇÃO PASSIVA",
    4: "BASE DE CÁLCULO, ALÍQUOTAS E REGRAS GERAIS",
    5: "ALÍQUOTAS DE REFERÊNCIA, REDUÇÕES, ALÍQUOTA ZERO E ANO TESTE",
    6: "SUJEIÇÃO PASSIVA, CONTRIBUINTE, RESPONSABILIDADE E SOLIDARIEDADE",
    7: "REGIMES DIFERENCIADOS – FUNDAMENTOS, LIMITES E REGRAS GERAIS",
    8: "CESTA BÁSICA NACIONAL, ESSENCIALIDADE E REDUÇÃO INTEGRAL",
    9: "CESTA ESTENDIDA, REDUÇÕES PARCIAIS (30% E 60%) E BENS DE CONSUMO AMPLIADO",
    10: "SAÚDE, EDUCAÇÃO E SERVIÇOS ESSENCIAIS",
    11: "SERVIÇOS FINANCEIROS, SEGUROS E OPERAÇÕES DE CRÉDITO",
    12: "PLANOS DE SAÚDE, PREVIDÊNCIA COMPLEMENTAR E CAPITALIZAÇÃO",
    13: "TRANSPORTE DE CARGAS E DE PASSAGEIROS",
    14: "COMBUSTÍVEIS, LUBRIFICANTES, ENERGIA ELÉTRICA E GÁS",
    15: "BENS IMÓVEIS, INCORPORAÇÃO IMOBILIÁRIA E CONSTRUÇÃO CIVIL",
    16: "ECONOMIA DIGITAL, PLATAFORMAS E SERVIÇOS ELETRÔNICOS",
    17: "OPERAÇÕES INTERNACIONAIS, EXPORTAÇÕES E ZONAS ESPECIAIS",
    18: "DEVOLUÇÃO (CASHBACK) – ADMINISTRAÇÃO INTEGRADA, CÁLCULO E MARCOS",
    19: "NÃO CUMULATIVIDADE, DIREITO AO CRÉDITO E APROPRIAÇÃO",
    20: "RESSARCIMENTO, COMPENSAÇÃO E TRANSFERÊNCIA DE CRÉDITOS",
    21: "OBRIGAÇÕES ACESSÓRIAS, ESCRITURAÇÃO E DOCUMENTOS FISCAIS",
    22: "APURAÇÃO, RECOLHIMENTO E PAGAMENTO DO IBS E DA CBS",
    23: "PENALIDADES, MULTAS E RESPONSABILIDADES",
    24: "PROCESSO ADMINISTRATIVO, CONTENCIOSO E JULGAMENTO",
    25: "COMITÊ GESTOR DO IBS – ESTRUTURA, COMPETÊNCIAS E GOVERNANÇA",
    26: "DISTRIBUIÇÃO DE RECEITAS, PARTILHA E REPASSES FEDERATIVOS",
    27: "FUNDOS DE COMPENSAÇÃO, EQUALIZAÇÃO E DESENVOLVIMENTO REGIONAL",
    28: "REGIMES ESPECÍFICOS REMANESCENTES E SETORES SENSÍVEIS",
    29: "REGIMES FAVORECIDOS, SIMPLIFICADOS E O ENQUADRAMENTO DO SIMPLES",
    30: "ADMINISTRAÇÃO DA CBS, COMPETÊNCIAS DA RFB E INTEGRAÇÃO COM O IBS",
    31: "DISPOSIÇÕES TRANSITÓRIAS GERAIS",
    32: "DISPOSIÇÕES FINAIS, REVOGAÇÕES E CONSOLIDAÇÃO NORMATIVA",
}
